import Head from 'next/head'
import Navbar from '../components/Navbar'
import Client from './Client'
import Contact from './Contact'

import Footer from './Footer'
import HOMEPAGE from './homePage'
import Service from './Service'
import Work from './Work'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hoo.png" />android-chrome-384x384.png
      </Head>

      <Navbar/>
      <HOMEPAGE/>
      <Service/>
      <Work/>
      <Client/>
      <Contact/>
      
      <Footer/>
      
  
      
     
    </div>
  )
}
